import { TestBed, ComponentFixture,  } from '@angular/core/testing';
import { DebugElement } from '@angular/core';
import { By } from '@angular/platform-browser';
import { HttpModule } from '@angular/http';
import { JokeComponent } from './joke.component';
import { JokeService } from '../joke.service';
import { Observable } from 'rxjs/Rx';

describe('Component: Joke Component', () => {
	let fixture: ComponentFixture<JokeComponent>;
	let component: JokeComponent;
	let jokeService: any;
	let de: DebugElement;
	beforeEach(() => {
		// jokeService = {
		// 	getJoke: () => Observable.of('FAKE JOKE')
		// };
		// component = new JokeComponent(jokeService);
		TestBed.configureTestingModule({
			declarations: [JokeComponent],
			imports: [HttpModule],
			providers: [
				JokeService
				// {provide: JokeService, useValue: jokeService}
			]
		});

		fixture = TestBed.createComponent(JokeComponent);
		component = fixture.componentInstance;
		jokeService = TestBed.get(JokeService);
		de = fixture.debugElement;
	});

	it('should add 1 + 1', () => {
		expect(1 + 1).toEqual(2);
	});

	// isolated test
	it('should gave title of "Chuck Norris Jokes"', () => {
		expect(component.title).toEqual('Chuck Norris Jokes');
	});

	it ('should get set the joke property when the component is initialized', () => {
		// main benefit of using the TestBed is that we can actually get 
		// a handle on the view and test the template
		spyOn(jokeService, 'getJoke').and.returnValue(Observable.of('FAKE JOKE'));
		fixture.detectChanges(); // Will trigger ngOnInit
		expect(component.joke).toEqual('FAKE JOKE');
	});

	it('should have joke content on the page', () => {
		spyOn(jokeService, 'getJoke').and.returnValue(Observable.of('FAKE JOKE'));
		fixture.detectChanges();

		let el = de.query(By.css('.jokeCssClass')).nativeElement;
		expect(el.textContent).toEqual('FAKE JOKE');
	});
});

// --------------------------------
// Testing without 
// --------------------------------

// import { JokeComponent } from './joke.component';
// import { Observable } from 'rxjs/Rx';

// describe('Component: Joke Component', () => {
// 	let component: JokeComponent;
// 	let jokeService: any;
// 	beforeEach(() => {
// 		jokeService = {
// 			getJoke: () => Observable.of('FAKE JOKE')
// 		};
// 		component = new JokeComponent(jokeService);
// 	});

// 	it('should add 1 + 1', () => {
// 		expect(1 + 1).toEqual(2);
// 	});

// 	// isolated test
// 	it('should gave title of "Chuck Norris Jokes"', () => {
// 		expect(component.title).toEqual('Chuck Norris Jokes');
// 	});

// 	it ('should get set the joke property when the component is initialized', () => {
// 		component.ngOnInit();
// 		expect(component.joke).toEqual('FAKE JOKE');
// 	});
// });

// --------------------------------
// Generated by Angular CLI
// --------------------------------

/* tslint:disable:no-unused-variable */
// import { async, ComponentFixture, TestBed } from '@angular/core/testing';
// import { By } from '@angular/platform-browser';
// import { DebugElement } from '@angular/core';

// import { JokeComponent } from './joke.component';

// describe('JokeComponent', () => {
// 	let component: JokeComponent;
// 	let fixture: ComponentFixture<JokeComponent>;

// 	beforeEach(async(() => {
// 		TestBed.configureTestingModule({
// 			declarations: [ JokeComponent ]
// 		})
// 		.compileComponents();
// 	}));

// 	beforeEach(() => {
// 		fixture = TestBed.createComponent(JokeComponent);
// 		component = fixture.componentInstance;
// 		fixture.detectChanges();
// 	});

// 	it('should create', () => {
// 		expect(component).toBeTruthy();
// 	});
// });
